package org.sdrc.scpsassam.repository;

import org.sdrc.scpsassam.domain.IndicatorClassification;
import org.sdrc.scpsassam.domain.IndicatorClassificationIndicatorUnitSubgroupMapping;
import org.sdrc.scpsassam.domain.IndicatorUnitSubgroup;

public interface IndicatorClassification_Ius_Mapping_Repository {
	
	
	public IndicatorClassificationIndicatorUnitSubgroupMapping save(IndicatorClassificationIndicatorUnitSubgroupMapping ic_ius);

	public IndicatorClassificationIndicatorUnitSubgroupMapping findByIndicatorClassificationAndIndicatorUnitSubgroup(IndicatorClassification icSubSector, IndicatorUnitSubgroup ius);

}